/* 11d. LTE turbo decoder + CRC-24A — the PDSCH transport-block primitive.
 *
 * The shared/downlink data channel (PDSCH) that carries a SIB is protected by
 * the rate-1/3 turbo code of 36.212 5.1.3.2: two 8-state recursive systematic
 * convolutional constituents joined by a QPP interleaver, the pair rate-matched
 * (5.1.4.1) into the E soft bits actually transmitted. Nothing here is about a
 * subscriber — a SIB1 transport block is the cell's own broadcast identity.
 *
 * The chain, receive side:
 *   E descrambled LLRs (>0 favours bit 0)
 *     -> turbo rate de-match  (circular-buffer inverse, sub-block deinterleave)
 *     -> iterative max-log-MAP BCJR between the two constituents
 *     -> K hard bits -> CRC-24A (D^24+D^23+D^18+D^17+D^14+D^11+D^10+D^7+D^6+
 *        D^5+D^4+D^3+D+1). CRC pass => the K-24 payload bits.
 *
 * QPP parameters f1/f2 come from the full 36.212 Table 5.1.3-3 embedded below
 * (generated by proto/qpp.py, the single source shared with the numpy twin).
 * The readable statement of the whole thing is atkdsp.reference.lte_turbo_* /
 * lte_crc24a; tests/test_cross_check.py holds the C to it.
 *
 * Turbo decode is NOT a per-sample hot path (a SIB arrives every 80 ms and its
 * transport block is a few hundred bits), so — unlike the streaming kernels —
 * this call allocates its scratch. It frees everything before it returns. */
#include "internal.h"

/* ---- QPP interleaver table (36.212 Table 5.1.3-3), K,f1,f2 -------------- */
static const int QPP_TABLE[][3] = {
    {40,3,10},{48,7,12},{56,19,42},{64,7,16},{72,7,18},{80,11,20},{88,5,22},
    {96,11,24},{104,7,26},{112,41,84},{120,103,90},{128,15,32},{136,9,34},
    {144,17,108},{152,9,38},{160,21,120},{168,101,84},{176,21,44},
    {184,57,46},{192,23,48},{200,13,50},{208,27,52},{216,11,36},{224,27,56},
    {232,85,58},{240,29,60},{248,33,62},{256,15,32},{264,17,198},
    {272,33,68},{280,103,210},{288,19,36},{296,19,74},{304,37,76},
    {312,19,78},{320,21,120},{328,21,82},{336,115,84},{344,193,86},
    {352,21,44},{360,133,90},{368,81,46},{376,45,94},{384,23,48},
    {392,243,98},{400,151,40},{408,155,102},{416,25,52},{424,51,106},
    {432,47,72},{440,91,110},{448,29,168},{456,29,114},{464,247,58},
    {472,29,118},{480,89,180},{488,91,122},{496,157,62},{504,55,84},
    {512,31,64},{528,17,66},{544,35,68},{560,227,420},{576,65,96},
    {592,19,74},{608,37,76},{624,41,234},{640,39,80},{656,185,82},
    {672,43,252},{688,21,86},{704,155,44},{720,79,120},{736,139,92},
    {752,23,94},{768,217,48},{784,25,98},{800,17,80},{816,127,102},
    {832,25,52},{848,239,106},{864,17,48},{880,137,110},{896,215,112},
    {912,29,114},{928,15,58},{944,147,118},{960,29,60},{976,59,122},
    {992,65,124},{1008,55,84},{1024,31,64},{1056,17,66},{1088,171,204},
    {1120,67,140},{1152,35,72},{1184,19,74},{1216,39,76},{1248,19,78},
    {1280,199,240},{1312,21,82},{1344,211,252},{1376,21,86},{1408,43,88},
    {1440,149,60},{1472,45,92},{1504,49,846},{1536,71,48},{1568,13,28},
    {1600,17,80},{1632,25,102},{1664,183,104},{1696,55,954},{1728,127,96},
    {1760,27,110},{1792,29,112},{1824,29,114},{1856,57,116},{1888,45,354},
    {1920,31,120},{1952,59,610},{1984,185,124},{2016,113,420},{2048,31,64},
    {2112,17,66},{2176,171,136},{2240,209,420},{2304,253,216},
    {2368,367,444},{2432,265,456},{2496,181,468},{2560,39,80},{2624,27,164},
    {2688,127,504},{2752,143,172},{2816,43,88},{2880,29,300},{2944,45,92},
    {3008,157,188},{3072,47,96},{3136,13,28},{3200,111,240},{3264,443,204},
    {3328,51,104},{3392,51,212},{3456,451,192},{3520,257,220},{3584,57,336},
    {3648,313,228},{3712,271,232},{3776,179,236},{3840,331,120},
    {3904,363,244},{3968,375,248},{4032,127,168},{4096,31,64},{4160,33,130},
    {4224,43,264},{4288,33,134},{4352,477,408},{4416,35,138},{4480,233,280},
    {4544,357,142},{4608,337,480},{4672,37,146},{4736,71,444},{4800,71,120},
    {4864,37,152},{4928,39,462},{4992,127,234},{5056,39,158},{5120,39,80},
    {5184,31,96},{5248,113,902},{5312,41,166},{5376,251,336},{5440,43,170},
    {5504,21,86},{5568,43,174},{5632,45,176},{5696,45,178},{5760,161,120},
    {5824,89,182},{5888,323,184},{5952,47,186},{6016,23,94},{6080,47,190},
    {6144,263,480},
};
#define QPP_N 188

/* Internal accessors so src/lte_sib1_phy.c can walk the valid code-block
 * sizes for its CRC-gated K search. Not part of the ABI. */
int atk_qpp_count(void) { return QPP_N; }
int atk_qpp_k(int i) { return (i >= 0 && i < QPP_N) ? QPP_TABLE[i][0] : -1; }

/* turbo sub-block column permutation (36.212 Table 5.1.4-1) */
static const int TPERM[32] = {
    0,16,8,24,4,20,12,28,2,18,10,26,6,22,14,30,
    1,17,9,25,5,21,13,29,3,19,11,27,7,23,15,31 };

#define NEG (-1e18)

/* Extrinsic scaling for max-log-MAP. The max-log approximation overestimates
 * the extrinsic magnitude; multiplying it by ~0.7-0.75 before it feeds the
 * other constituent decoder recovers most of the gap to full log-MAP —
 * ~0.3-0.5 dB on the SIB turbo blocks, free. Must match _TURBO_EXT_SCALE in
 * atkdsp.reference. 1.0 = plain max-log-MAP (the old behaviour). */
#define TURBO_EXT_SCALE 0.75

/* RSC trellis: state = (r1<<2)|(r2<<1)|r3, r1 newest.
 * a = u^r2^r3 (feedback g0=1+D^2+D^3); z = a^r1^r3 (parity g1=1+D+D^3);
 * ns = (a<<2)|(r1<<1)|r2. TAIL_U[s] drives a=0. */
static int NS[8][2], PAR[8][2], TAIL_U[8];
static void build_trellis(void) {
    int s, u, r1, r2, r3, a, z;
    for (s = 0; s < 8; ++s) {
        r1 = (s >> 2) & 1; r2 = (s >> 1) & 1; r3 = s & 1;
        for (u = 0; u < 2; ++u) {
            a = u ^ r2 ^ r3;
            z = a ^ r1 ^ r3;
            NS[s][u]  = (a << 2) | (r1 << 1) | r2;
            PAR[s][u] = z;
        }
        TAIL_U[s] = r2 ^ r3;
    }
}

/* ---- CRC-24A (36.212 5.1.1) ------------------------------------------- */
/* gCRC24A = D^24+D^23+D^18+D^17+D^14+D^11+D^10+D^7+D^6+D^5+D^4+D^3+D+1. */
#define G24A 0x1864CFBu
static unsigned crc24a_reg(const signed char *bits, int nbits) {
    unsigned reg = 0; int k, i;
    for (k = 0; k < nbits; ++k) {
        reg = (reg << 1) | (unsigned)(bits[k] & 1);
        if (reg & (1u << 24)) reg ^= G24A;
    }
    for (i = 0; i < 24; ++i) { reg <<= 1; if (reg & (1u << 24)) reg ^= G24A; }
    return reg & 0xFFFFFFu;
}

int atkdsp_lte_crc24a(const signed char *bits, int nbits, signed char *out24) {
    unsigned reg; int i;
    if (!bits || nbits < 0 || !out24) return ATKDSP_E_ARG;
    reg = crc24a_reg(bits, nbits);
    for (i = 0; i < 24; ++i) out24[i] = (signed char)((reg >> (23 - i)) & 1);
    return ATKDSP_OK;
}

/* bits = payload + 24 CRC; 1 if the CRC checks. */
static int crc24a_check(const signed char *bits, int total) {
    unsigned reg = crc24a_reg(bits, total - 24), rx = 0; int i;
    for (i = 0; i < 24; ++i) rx = (rx << 1) | (unsigned)(bits[total - 24 + i] & 1);
    return reg == rx;
}

/* ---- QPP lookup + permutation ----------------------------------------- */
static int qpp_lookup(int K, int *f1, int *f2) {
    int lo = 0, hi = QPP_N - 1;
    while (lo <= hi) {
        int mid = (lo + hi) >> 1;
        if (QPP_TABLE[mid][0] == K) { *f1 = QPP_TABLE[mid][1]; *f2 = QPP_TABLE[mid][2]; return 1; }
        if (QPP_TABLE[mid][0] < K) lo = mid + 1; else hi = mid - 1;
    }
    return 0;
}
/* pi[i] = (f1*i + f2*i*i) mod K, in 64-bit to avoid overflow. */
static void qpp_perm(int K, int f1, int f2, int *pi) {
    int i;
    for (i = 0; i < K; ++i) {
        long long v = ((long long)f1 * i + (long long)f2 * i * i) % K;
        pi[i] = (int)v;
    }
}

/* ---- turbo sub-block maps (36.212 5.1.4.1.1) -------------------------- */
/* For D data bits: R rows x 32 cols null-padded. idx01[p]/idx2[p] give the
 * source index into 0..D-1 for each of the KPi=32R positions (-1 = null). */
static void subblock_maps(int D, int *idx01, int *idx2, int *R_out, int *KPi_out) {
    const int C = 32;
    int R = (D + C - 1) / C;
    int KPi = R * C;
    int ND = KPi - D;
    int p, k;
    /* padded[j] for j in 0..KPi-1: -1 for the first ND, then 0..D-1 */
    /* idx01[p]: p -> c=p/R, r=p%R ; source padded[r*32 + TPERM[c]] */
    for (p = 0; p < KPi; ++p) {
        int c = p / R, r = p % R;
        int src = r * C + TPERM[c];         /* index into padded */
        idx01[p] = (src < ND) ? -1 : (src - ND);
    }
    /* idx2[k]: pi2 = (TPERM[k/R] + 32*(k%R) + 1) mod KPi ; source padded[pi2] */
    for (k = 0; k < KPi; ++k) {
        int pi2 = (TPERM[k / R] + C * (k % R) + 1) % KPi;
        idx2[k] = (pi2 < ND) ? -1 : (pi2 - ND);
    }
    *R_out = R; *KPi_out = KPi;
}

/* rate de-match: E LLRs -> d0,d1,d2 (each length D). Ncb = 3*KPi (no
 * soft-buffer limiting for a broadcast TB); the read starts at 36.212
 * 5.1.4.1.2's k0 = R*(2*ceil(Ncb/(8R))*rv + 2). SIB1 is sent with RV 0, 2, 3,
 * 1 in turn; this used to assume rv=0, so three SIB1 transmissions in four
 * never passed CRC on air (Bill's B13 recording, 2026-09-26). */
static void rate_dematch(const double *e_llr, int E, int D, int rv,
                         double *d0, double *d1, double *d2) {
    int R, KPi, Ncb, j, k, kk, i;
    int *idx01 = (int *)malloc(sizeof(int) * (size_t)(D + 32));
    int *idx2  = (int *)malloc(sizeof(int) * (size_t)(D + 32));
    /* size idx arrays to KPi; D+32 >= KPi since KPi <= D+31 */
    signed char *isnull;
    double *w, *v0, *v1, *v2;
    subblock_maps(D, idx01, idx2, &R, &KPi);
    Ncb = 3 * KPi;
    isnull = (signed char *)calloc((size_t)Ncb, 1);
    w = (double *)calloc((size_t)Ncb, sizeof(double));
    /* null map: [0,KPi) = v0 (idx01<0); [KPi..) even = v1 (idx01<0); odd = v2 */
    for (i = 0; i < KPi; ++i) {
        if (idx01[i] < 0) { isnull[i] = 1; isnull[KPi + 2 * i] = 1; }
        if (idx2[i]  < 0) isnull[KPi + 2 * i + 1] = 1;
    }
    j = R * (2 * ((Ncb + 8 * R - 1) / (8 * R)) * (rv & 3) + 2);   /* k0 */
    k = 0;
    while (k < E) {
        int pos = j % Ncb;
        if (!isnull[pos]) { w[pos] += e_llr[k]; ++k; }
        ++j;
    }
    v0 = w;                                     /* w[:KPi] */
    v1 = (double *)malloc(sizeof(double) * (size_t)KPi);
    v2 = (double *)malloc(sizeof(double) * (size_t)KPi);
    for (i = 0; i < KPi; ++i) { v1[i] = w[KPi + 2 * i]; v2[i] = w[KPi + 2 * i + 1]; }
    for (i = 0; i < D; ++i) { d0[i] = 0.0; d1[i] = 0.0; d2[i] = 0.0; }
    for (kk = 0; kk < KPi; ++kk) {
        if (idx01[kk] >= 0) { d0[idx01[kk]] += v0[kk]; d1[idx01[kk]] += v1[kk]; }
        if (idx2[kk]  >= 0) d2[idx2[kk]] += v2[kk];
    }
    free(idx01); free(idx2); free(isnull); free(w); free(v1); free(v2);
}

/* ---- max-log-MAP BCJR for one constituent ----------------------------- */
/* sys/par length n=K+3 (incl. tail); apri length K. Writes ext[K]. Terminated
 * (both constituents are trellis-terminated). Scratch alpha/beta caller-owned,
 * each (n+1)*8 doubles. */
static void bcjr(const double *sys, const double *par, const double *apri,
                 int K, double *alpha, double *beta, double *ext) {
    const int n = K + 3;
    int k, s, u;
    for (k = 0; k <= n; ++k) for (s = 0; s < 8; ++s) alpha[k * 8 + s] = NEG;
    alpha[0] = 0.0;
    for (k = 0; k < n; ++k) {
        const double ap = (k < K) ? apri[k] : 0.0;
        const double sl = sys[k], pl = par[k];
        for (s = 0; s < 8; ++s) {
            const double a = alpha[k * 8 + s];
            if (a <= NEG) continue;
            for (u = 0; u < 2; ++u) {
                const int ns = NS[s][u], z = PAR[s][u];
                double g = 0.5 * (sl * (1 - 2 * u) + pl * (1 - 2 * z)
                                  + (k < K ? ap * (1 - 2 * u) : 0.0));
                double v = a + g;
                if (v > alpha[(k + 1) * 8 + ns]) alpha[(k + 1) * 8 + ns] = v;
            }
        }
    }
    for (k = 0; k <= n; ++k) for (s = 0; s < 8; ++s) beta[k * 8 + s] = NEG;
    beta[n * 8 + 0] = 0.0;                        /* terminated at state 0 */
    for (k = n - 1; k >= 0; --k) {
        const double ap = (k < K) ? apri[k] : 0.0;
        const double sl = sys[k], pl = par[k];
        for (s = 0; s < 8; ++s) {
            double best = NEG;
            for (u = 0; u < 2; ++u) {
                const int ns = NS[s][u], z = PAR[s][u];
                double g = 0.5 * (sl * (1 - 2 * u) + pl * (1 - 2 * z)
                                  + (k < K ? ap * (1 - 2 * u) : 0.0));
                double v = beta[(k + 1) * 8 + ns] + g;
                if (v > best) best = v;
            }
            beta[k * 8 + s] = best;
        }
    }
    for (k = 0; k < K; ++k) {
        const double ap = apri[k], sl = sys[k], pl = par[k];
        double m1 = NEG, m0 = NEG;
        for (s = 0; s < 8; ++s) {
            const double a = alpha[k * 8 + s];
            if (a <= NEG) continue;
            for (u = 0; u < 2; ++u) {
                const int ns = NS[s][u], z = PAR[s][u];
                double g = 0.5 * (sl * (1 - 2 * u) + pl * (1 - 2 * z) + ap * (1 - 2 * u));
                double v = a + g + beta[(k + 1) * 8 + ns];
                if (u) { if (v > m1) m1 = v; } else { if (v > m0) m0 = v; }
            }
        }
        ext[k] = (m0 - m1) - sl - ap;            /* extrinsic */
    }
}

/* ---- turbo decode from de-rate-matched d0/d1/d2 (each length K+4) ------ */
/* out_bits: K bits (info + 24 CRC). Returns 0 ok, <0 on alloc failure. */
static int turbo_decode_d(const double *d0, const double *d1, const double *d2,
                          int K, int iters, signed char *out_bits) {
    int f1, f2, k, it;
    int *pi, *inv;
    double *sys1, *sys2, *par1, *par2, *apri, *e1, *e2, *tmp, *alpha, *beta;
    if (!qpp_lookup(K, &f1, &f2)) return ATKDSP_E_ARG;
    pi   = (int *)malloc(sizeof(int) * (size_t)K);
    inv  = (int *)malloc(sizeof(int) * (size_t)K);
    sys1 = (double *)malloc(sizeof(double) * (size_t)(K + 3));
    sys2 = (double *)malloc(sizeof(double) * (size_t)(K + 3));
    par1 = (double *)malloc(sizeof(double) * (size_t)(K + 3));
    par2 = (double *)malloc(sizeof(double) * (size_t)(K + 3));
    apri = (double *)calloc((size_t)K, sizeof(double));
    e1   = (double *)malloc(sizeof(double) * (size_t)K);
    e2   = (double *)malloc(sizeof(double) * (size_t)K);
    tmp  = (double *)malloc(sizeof(double) * (size_t)K);
    alpha = (double *)malloc(sizeof(double) * (size_t)((K + 4) * 8));
    beta  = (double *)malloc(sizeof(double) * (size_t)((K + 4) * 8));
    if (!pi || !inv || !sys1 || !sys2 || !par1 || !par2 || !apri ||
        !e1 || !e2 || !tmp || !alpha || !beta) {
        free(pi); free(inv); free(sys1); free(sys2); free(par1); free(par2);
        free(apri); free(e1); free(e2); free(tmp); free(alpha); free(beta);
        return ATKDSP_E_NOMEM;
    }
    qpp_perm(K, f1, f2, pi);
    for (k = 0; k < K; ++k) inv[pi[k]] = k;
    /* sys1 = [d0[:K], tail1_sys=(d0[K],d2[K],d1[K+1])] */
    for (k = 0; k < K; ++k) sys1[k] = d0[k];
    sys1[K] = d0[K]; sys1[K + 1] = d2[K]; sys1[K + 2] = d1[K + 1];
    /* sys2 = [d0[pi[:]], tail2_sys=(d0[K+2],d2[K+2],d1[K+3])] */
    for (k = 0; k < K; ++k) sys2[k] = d0[pi[k]];
    sys2[K] = d0[K + 2]; sys2[K + 1] = d2[K + 2]; sys2[K + 2] = d1[K + 3];
    /* par1 = [d1[:K], d1[K], d0[K+1], d2[K+1]] */
    for (k = 0; k < K; ++k) par1[k] = d1[k];
    par1[K] = d1[K]; par1[K + 1] = d0[K + 1]; par1[K + 2] = d2[K + 1];
    /* par2 = [d2[:K], d1[K+2], d0[K+3], d2[K+3]] */
    for (k = 0; k < K; ++k) par2[k] = d2[k];
    par2[K] = d1[K + 2]; par2[K + 1] = d0[K + 3]; par2[K + 2] = d2[K + 3];

    for (it = 0; it < iters; ++it) {
        bcjr(sys1, par1, apri, K, alpha, beta, e1);
        for (k = 0; k < K; ++k)                          /* e1 interleaved */
            tmp[k] = TURBO_EXT_SCALE * e1[pi[k]];
        bcjr(sys2, par2, tmp, K, alpha, beta, e2);
        for (k = 0; k < K; ++k)                          /* e2 deinterleaved */
            apri[k] = TURBO_EXT_SCALE * e2[inv[k]];
    }
    bcjr(sys1, par1, apri, K, alpha, beta, e1);
    for (k = 0; k < K; ++k) {
        double llr = sys1[k] + apri[k] + e1[k];          /* sys1[k]=d0[k]=sys */
        out_bits[k] = (signed char)(llr < 0.0 ? 1 : 0);
    }
    free(pi); free(inv); free(sys1); free(sys2); free(par1); free(par2);
    free(apri); free(e1); free(e2); free(tmp); free(alpha); free(beta);
    return ATKDSP_OK;
}

/* ---- public API ------------------------------------------------------- */
int atkdsp_lte_turbo_decode(const float *llr, size_t E, int K, int rv,
                            int iters, signed char *out) {
    double *e = NULL, *d0 = NULL, *d1 = NULL, *d2 = NULL;
    signed char *bits = NULL;
    int D = K + 4, rc, i, ok = 0;
    if (!llr || !out || K <= 0 || E == 0) return ATKDSP_E_ARG;
    { int f1, f2; if (!qpp_lookup(K, &f1, &f2)) return ATKDSP_E_ARG; }
    if (iters <= 0) iters = 8;
    build_trellis();
    e    = (double *)malloc(sizeof(double) * E);
    d0   = (double *)malloc(sizeof(double) * (size_t)D);
    d1   = (double *)malloc(sizeof(double) * (size_t)D);
    d2   = (double *)malloc(sizeof(double) * (size_t)D);
    bits = (signed char *)malloc((size_t)K);
    if (!e || !d0 || !d1 || !d2 || !bits) { rc = ATKDSP_E_NOMEM; goto done; }
    for (i = 0; i < (int)E; ++i) e[i] = (double)llr[i];
    rate_dematch(e, (int)E, D, rv, d0, d1, d2);
    rc = turbo_decode_d(d0, d1, d2, K, iters, bits);
    if (rc != ATKDSP_OK) goto done;
    ok = crc24a_check(bits, K);
    if (ok) for (i = 0; i < K - 24; ++i) out[i] = bits[i];
    rc = ok ? 1 : 0;
done:
    free(e); free(d0); free(d1); free(d2); free(bits);
    return rc;
}
